<a href="https://colab.research.google.com/github/Vamshi13212/Assignments_here/blob/main/Copy_of_Assessment2B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###### Assessment

###### I am going to provide two .csv files , you are supposed to work on them and have to provide solutions to the following problems

###### import necessary libraries

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

###### merge those two csv files (after getting as dataframes, get them as a single dataframe)

In [6]:
df1=pd.read_csv("/content/college_1.csv")
df2=pd.read_csv("/content/college_2.csv")
df = df1.append([df2],ignore_index=True)
df

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
0,A.Dharani,82.0,20.0,24500,24500,Computer Science and Engineering,0,NaN,NaN
1,V.JEEVITHA,82.0,20.0,21740,21740,Computer Science and Engineering,0,NaN,NaN
2,HEMAVATHI.R,100.0,100.0,19680,19680,Computer Science and Engineering,0,NaN,NaN
3,Mugunthan S,100.0,47.0,10610,10610,Computer Science and Engineering,0,NaN,NaN
4,Sathammai.S,100.0,8.0,8980,8980,Computer Science and Engineering,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
114,praveen raj j,24.0,0.0,2380,2380,Computer Science and Engineering,0,-1.0,0.0
115,AMARNATH D,-1.0,12.0,1890,1890,Electronics and Communication Engineering,0,52.0,-1.0
116,bala,32.0,0.0,1720,1720,Electronics and Communication Engineering,0,49.0,-1.0
117,XY Z,-1.0,-1.0,0,0,Computer Science and Engineering,0,20.0,-1.0
118,Hariharan,-1.0,-1.0,0,0,Computer Science and Engineering,0,-1.0,0.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    119 non-null    object
 1   python                  119 non-null    float64
 2   mysql                   119 non-null    float64
 3   Previous Geekions       119 non-null    int64
 4   CodeKata Score          119 non-null    int64
 5   Department              119 non-null    object
 6   Rising                  119 non-null    int64
 7   python_en               35 non-null     float64
 8   computational_thinking  35 non-null     float64
dtypes: float64(4), int64(3), object(2)
memory usage: 8.5+ KB

###### Take each csv file , split that csv file into multiple categories (example csv files are added in the repo)

###### consider if the codekata score exceeds 15000 points(present week) then make a csv on those observations as Exceeded expectations.csv

In [10]:
Exceeded_expectations=df.loc[df["CodeKata Score"]>=15000]
Exceeded_expectations.to_csv("Exceeded_expectations")
Exceeded_expectations

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
0,A.Dharani,82.0,20.0,24500,24500,Computer Science and Engineering,0,NaN,NaN
1,V.JEEVITHA,82.0,20.0,21740,21740,Computer Science and Engineering,0,NaN,NaN
2,HEMAVATHI.R,100.0,100.0,19680,19680,Computer Science and Engineering,0,NaN,NaN
84,ASHOK KUMAR K,100.0,31.0,19400,19400,Electronics and Electrical Engineering,0,0.0,9.0

###### if  10000<codekata score<15000   (Reached_expectations.csv)

In [12]:
Reached_expectations=df.loc[(df["CodeKata Score"] >=10000) & (df["CodeKata Score"]<15000)]
Reached_expectations.to_csv("Reached_expectations")
Reached_expectations

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
3,Mugunthan S,100.0,47.0,10610,10610,Computer Science and Engineering,0,NaN,NaN
85,Chandru,0.0,0.0,14150,14490,Computer Science and Engineering,340,20.0,0.0
86,Ganesh Ramkumar R,-1.0,24.0,8790,10790,Computer Science and Engineering,2000,55.0,6.0
87,Bodipudi Harini,-1.0,35.0,10040,10040,Electronics and Communication Engineering,0,0.0,-1.0

###### if  7000<codekata score<10000   (Needs_Improvement.csv)

In [13]:
Needs_improvement=df.loc[(df["CodeKata Score"] >=7000) & (df["CodeKata Score"]<10000)]
Needs_improvement.to_csv("Needs_Improvement")
Needs_improvement

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
4,Sathammai.S,100.0,8.0,8980,8980,Computer Science and Engineering,0,NaN,NaN
5,NIVEESHWAR S,100.0,0.0,8200,8200,Computer Science and Engineering,0,NaN,NaN
6,KALAIARASAN K,85.0,47.0,7750,7880,Electronics and Communication Engineering,130,NaN,NaN
7,MOHAMED ZUBAIR AHMED,82.0,4.0,7020,7020,Computer Science and Engineering,0,NaN,NaN
88,VIINU V P,-1.0,24.0,9150,9150,Electronics and Electrical Engineering,0,100.0,-1.0
89,Poojitha Y,0.0,35.0,7210,8970,Computer Science and Engineering,1760,78.0,0.0
90,Gowtham Chandrasekaran,-1.0,0.0,7250,8950,Computer Science and Engineering,1700,0.0,3.0
91,Gowtham R,-1.0,4.0,8650,8650,Electronics and Communication Engineering,0,60.0,6.0
92,shifak N,58.0,0.0,5180,8320,Electronics and Electrical Engineering,3140,0.0,0.0
93,Balaji,-1.0,20.0,6170,8160,Electronics and Electrical Engineering,1990,100.0,0.0
94,Rushitha,-1.0,62.0,7470,8090,Computer Science and Engineering,620,15.0,9.0
95,Balaraman Muthupandi,-1.0,0.0,7670,8050,Computer Science and Engineering,380,9.0,0.0
96,JPradhap,100.0,0.0,7340,8030,Electronics and Electrical Engineering,690,0.0,0.0
97,SRIRAMKUMAR B,-1.0,0.0,6400,7940,Computer Science and Engineering,1540,0.0,0.0
98,Praneetha,-1.0,100.0,7170,7730,Electronics and Communication Engineering,560,23.0,-1.0
99,Rahul Raj K,-1.0,0.0,6280,7640,Computer Science and Engineering,1360,0.0,0.0
100,Guhan S,-1.0,35.0,7310,7630,Electronics and Communication Engineering,320,72.0,39.0
101,Suryarajan S,-1.0,31.0,6710,7550,Computer Science and Engineering,840,63.0,0.0

###### if  codekate score < 7000        (Unsatisfactory.csv)

In [14]:
Unsatisfactory=df.loc[df["CodeKata Score"]<7000]
Unsatisfactory.to_csv("Unsatisfactory")
Unsatisfactory

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
8,J.SUGANTHI,27.0,50.00,5860,5860,Electronics and Communication Engineering,0,NaN,NaN
9,thamizhpaana,29.0,0.00,5500,5500,Computer Science and Engineering,0,NaN,NaN
10,Iyappan Samiraj,50.0,24.00,5400,5400,Electronics and Communication Engineering,0,NaN,NaN
11,Ponniyamma.R,100.0,11.25,5380,5380,Computer Science and Engineering,0,NaN,NaN
12,SABAPATHI,100.0,0.00,5280,5280,Computer Science and Engineering,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
114,praveen raj j,24.0,0.00,2380,2380,Computer Science and Engineering,0,-1.0,0.0
115,AMARNATH D,-1.0,12.00,1890,1890,Electronics and Communication Engineering,0,52.0,-1.0
116,bala,32.0,0.00,1720,1720,Electronics and Communication Engineering,0,49.0,-1.0
117,XY Z,-1.0,-1.00,0,0,Computer Science and Engineering,0,20.0,-1.0
118,Hariharan,-1.0,-1.00,0,0,Computer Science and Engineering,0,-1.0,0.0

###### Average of previous week geekions vs this week geekions (i.e Previous Geekions vs CodeKata Score)

In [17]:
average=df[["Previous Geekions","CodeKata Score"]]
average
fig=px.bar(average.mean(),title="Average of previous geek coins and codekata score",labels={'value':'Mean'})
fig

###### No of students participated

In [18]:
count=df["Name"].count()
print('No: of Students Participated = {}'.format(count))

No: of Students Participated = 119

###### #Average completion of python course or my_sql or python english or computational thinking

In [19]:
Avg_Completion=df.loc[(df['python']==100.0) | (df['mysql']==100.0) | (df['python_en']==100.0) | (df['computational_thinking']==100.0)]
print('Average completion of python course or my_sql or python english or computational thinking is: ',round(((len(Avg_Completion.index)/len(df.index))*100),2),'%')

Average completion of python course or my_sql or python english or computational thinking is:  38.66 %

###### rising star of the week (top 3 candidate who performed well in that particular week)

In [20]:
df.nlargest(3,'Rising')

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
92,shifak N,58.0,0.0,5180,8320,Electronics and Electrical Engineering,3140,0.0,0.0
86,Ganesh Ramkumar R,-1.0,24.0,8790,10790,Computer Science and Engineering,2000,55.0,6.0
102,Narasimhan Y L,-1.0,0.0,4800,6800,Computer Science and Engineering,2000,-1.0,0.0

###### Shining stars of the week (top 3 candidates who has highest geekions)

In [21]:
df.nlargest(3,'CodeKata Score')

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
0,A.Dharani,82.0,20.0,24500,24500,Computer Science and Engineering,0,NaN,NaN
1,V.JEEVITHA,82.0,20.0,21740,21740,Computer Science and Engineering,0,NaN,NaN
2,HEMAVATHI.R,100.0,100.0,19680,19680,Computer Science and Engineering,0,NaN,NaN

###### Department wise codekata performence (pie chart)

In [22]:
fig=px.pie(df,names='Department',values='CodeKata Score',title='Department wise codekata performence',hole=0.2)
fig.update_traces(textinfo='percent+label',textposition='inside')

###### Department wise toppers (horizantal bar graph or any visual representations of your choice)

In [23]:
Topper=px.scatter(df,x='Department',y='CodeKata Score',size='CodeKata Score',color='CodeKata Score',hover_data=['Name'],title='Department wise Topper')
Topper